# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rserving.proto\x12\rmflow.serving"$\n\x06Matrix\x12\r\n\x05value\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x03(\x05"1\n\nPredictReq\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.mflow.serving.Matrix"2\n\x0bPredictResp\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.mflow.serving.Matrix2R\n\x0cMFlowServing\x12\x42\n\x07Predict\x12\x19.mflow.serving.PredictReq\x1a\x1a.mflow.serving.PredictResp"\x00\x62\x06proto3'
)


_MATRIX = DESCRIPTOR.message_types_by_name["Matrix"]
_PREDICTREQ = DESCRIPTOR.message_types_by_name["PredictReq"]
_PREDICTRESP = DESCRIPTOR.message_types_by_name["PredictResp"]
Matrix = _reflection.GeneratedProtocolMessageType(
    "Matrix",
    (_message.Message,),
    {
        "DESCRIPTOR": _MATRIX,
        "__module__": "serving_pb2"
        # @@protoc_insertion_point(class_scope:mflow.serving.Matrix)
    },
)
_sym_db.RegisterMessage(Matrix)

PredictReq = _reflection.GeneratedProtocolMessageType(
    "PredictReq",
    (_message.Message,),
    {
        "DESCRIPTOR": _PREDICTREQ,
        "__module__": "serving_pb2"
        # @@protoc_insertion_point(class_scope:mflow.serving.PredictReq)
    },
)
_sym_db.RegisterMessage(PredictReq)

PredictResp = _reflection.GeneratedProtocolMessageType(
    "PredictResp",
    (_message.Message,),
    {
        "DESCRIPTOR": _PREDICTRESP,
        "__module__": "serving_pb2"
        # @@protoc_insertion_point(class_scope:mflow.serving.PredictResp)
    },
)
_sym_db.RegisterMessage(PredictResp)

_MFLOWSERVING = DESCRIPTOR.services_by_name["MFlowServing"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MATRIX._serialized_start = 32
    _MATRIX._serialized_end = 68
    _PREDICTREQ._serialized_start = 70
    _PREDICTREQ._serialized_end = 119
    _PREDICTRESP._serialized_start = 121
    _PREDICTRESP._serialized_end = 171
    _MFLOWSERVING._serialized_start = 173
    _MFLOWSERVING._serialized_end = 255
# @@protoc_insertion_point(module_scope)
